version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: go_postgres
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user -d api_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge